# Updated Custom Resource Definition for an Anvil.
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: app.arkea-gcp.net
spec:
  group: arkea-gcp.net
  versions:
    - name: v1
      served: true
      storage: false
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
              - address
              properties:
                address:
                  type: string
    - name: v2
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
              - address
              properties:
                address:
                  type: string
  scope: Namespaced
  names:
    plural: app
    singular: app
    kind: App
